import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";

import { McLaren } from "next/font/google";
import { MantineProvider } from "@mantine/core";

const mcLaren = McLaren({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mcLaren.className} ${mcLaren.className} antialiased`}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
